import { NgModule } from '@angular/core';

/* components npm */
import {
  ButtonRaisedModule,
  ButtonOutlinedModule,
  ButtonDropdownModule,
  ButtonLinkModule,
  MenuModule,
  ChipsModule,
  ChipsOutlinedModule,
  TooltipModule,
  CustomLoaderModule,
  NotificationsModule,
  CardsModule,
  HeaderModule,
  ToolbarModule,
  InputModule,
  AppBadgeModule,
  CardHubModule,
  BlankStateModule,
  SelectModule,
  DialogModule,
  TabsModule,
  SuperCardModule,
  TextAreaModule,
  DatepickerModule,
  UploadModule,
  TableModule,
  CheckboxModule,
  RadioModule,
  CounterModule,
  SwitchModule,
  FreeButtonsModule,
  TabButtonsModule,
  SnackbarModule,
  CommentsModule,
} from '@pricefyteam/system-design';

@NgModule({
  exports: [
    SelectModule,
    TextAreaModule,
    BlankStateModule,
    InputModule,
    ButtonRaisedModule,
    ButtonOutlinedModule,
    ButtonDropdownModule,
    ButtonLinkModule,
    MenuModule,
    ChipsModule,
    ChipsOutlinedModule,
    TooltipModule,
    CustomLoaderModule,
    NotificationsModule,
    CardsModule,
    HeaderModule,
    SuperCardModule,
    ToolbarModule,
    AppBadgeModule,
    DialogModule,
    TabsModule,
    CardHubModule,
    DatepickerModule,
    UploadModule,
    TableModule,
    CheckboxModule,
    RadioModule,
    CounterModule,
    SwitchModule,
    FreeButtonsModule,
    TabButtonsModule,
    SnackbarModule,
    CommentsModule,
  ],
})
export class DSModule {}
